name: Salesforce CI/CD

on:
  push:
    branches: [ main ]

env:
  ROOTDIR: 'force-app/main/default/'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --location=global

      # - name: Deploy to Manoj org
      #   run: |
      #     sf org login jwt --client-id ${{ secrets.SF_MANOJ_CONSUMER_KEY }} --jwt-key-file assets/Manoj/server.key.enc --username manoj@mvervedev.com --alias ManojOrg
      #     sf project deploy start --source-dir $ROOTDIR --target-org ManojOrg
      #     sf apex run test --target-org ManojOrg

      # - name: Deploy to Harish org
      #   run: |
      #     sf org login jwt --client-id ${{ secrets.SF_HARISH_CONSUMER_KEY }} --jwt-key-file assets/Harish/server.key --username harish@mverve.com --alias HarishOrg
      #     sf project deploy start --source-dir $ROOTDIR --target-org HarishOrg
      #     sf apex run test --target-org ManojOrg

      - name: Decrypt server key
        run: openssl aes-256-cbc -d -in assets/pradeep/server.key.enc -out assets/pradeep/server.key -k ${{ secrets.SERVER_KEY_PASSWORD_PRADEEP }} -pbkdf2
      
      - name: Deploy to Pradeep org
        run: |
          sf org login jwt --client-id ${{ secrets.SF_PRADEEP_CONSUMER_KEY }} --jwt-key-file assets/pradeep/server.key --username nspradeep53@gmail.com --alias PradeepOrg
          sf project deploy start --source-dir $ROOTDIR --target-org PradeepOrg
          sf apex run test --target-org ManojOrg

